# --- build stage ---
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY . .
RUN mvn clean package

# --- runtime stage ---
FROM tomcat:9.0

COPY server.xml /usr/local/tomcat/conf/server.xml

# RUN rm -rf /usr/local/tomcat/webapps/ROOT \
#     && rm -f /usr/local/tomcat/webapps/ROOT.war

COPY target/app /usr/local/tomcat/webapps/ROOT

CMD ["catalina.sh", "jpda", "run"]