# --- build stage ---
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY . .
RUN mvn clean package

# --- runtime stage ---
FROM tomcat:9.0

COPY server.xml /usr/local/tomcat/conf/server.xml
COPY --from=build /app/target/app.war /usr/local/tomcat/webapps/ROOT.war

CMD ["catalina.sh", "jpda", "run"]